### ISSUE TITLE
Jira 개설 설정 하기

### ISSUE THREAD

**Issue by notx2wice** [CoffeDiary/SimpleDiary_BackEnd#1]
jira 개설 설정 하기

**Comment by loiipa** [comment]
https://www.atlassian.com/ko/software/jira

**Comment by notx2wice** [comment]
https://coffeediary.atlassian.net/jira/software/projects/SIM/boards/1

**Comment by notx2wice** [comment]
https://coffeediary.atlassian.net/jira/software/projects/SIM/boards/1
이 주소로 만들었습니다.
