### ISSUE TITLE
https://www.atlassian.com/ko/software/jira

### ISSUE THREAD

**Issue by loiipa** [CoffeDiary/SimpleDiary_BackEnd#2]
https://www.atlassian.com/ko/software/jira

_Originally posted by @loiipa in https://github.com/CoffeDiary/SimpleDiary/issues/1#issuecomment-987873021_

꼭봐주세요

**Comment by notx2wice** [comment]
뭘 보라는 거쥬

**Comment by notx2wice** [comment]
https://coffeediary.atlassian.net/jira/software/projects/SIM/boards/1
