### ISSUE TITLE
이부분 CORS 처리 안됨

### ISSUE THREAD

**Issue by loiipa** [CoffeDiary/SimpleDiary_BackEnd#7]
https://github.com/CoffeDiary/SimpleDiary_BackEnd/blob/5fd7292e6dd05af9a2baeaa62d783699d9650d23/src/main/java/toy/first/coffeediary/config/CorsConfig.java#L18

localhost:8070으로 명시해줘야 진행 할 수 있음.

**Comment by loiipa** [comment]
config.addAllowedOrigin("*");
        config.addAllowedOrigin("http://**");

->
        config.addAllowedOrigin("http://localhost:8070");

**Comment by notx2wice** [comment]
이거 저번에 했던거 아넵네까? 다시 돌아 가있음??

**Comment by notx2wice** [comment]
다시 돌아가 있군 처리하겠으
